version: '3'
services:
  spring:
    build: .
    image: spring
    container_name: spring
    ports:
      - 80:8080
    depends_on:
      - mysql
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_DATABASE=docker
      - MYSQL_PASSWORD=changeme
      - MYSQL_USER=cedric
      - MYSQL_ROOT_PASSWORD=changeme
    volumes:
      - /srv/volumes/db-data:/var/lib/mysql
volumes:
  db-data:
